// Generated by https://quicktype.io

export interface PokemonResponse {
    data: Data;
}

export interface Data {
    pokemon_v2_pokemon: PokemonV2Pokemon[];
}

export interface PokemonV2Pokemon {
    id:   number;
    name: string;
}
